import './global.css'
import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/theme-provider'
import { inter } from '@/lib/fonts'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/header'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />

            {children}

            <div className='flex justify-center mt-4'>
              <Footer />
            </div>
          </ThemeProvider>
        </body>
      </html >
    </ClerkProvider>
  )
}
